---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${SECRET_DOMAIN}-staging-tls"
  namespace: cert-manager
spec:
  commonName: "${SECRET_DOMAIN}"
  dnsNames:
    - "${SECRET_DOMAIN}"
    - "*.${SECRET_DOMAIN}"
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  secretName: "${SECRET_DOMAIN}-staging-tls"
