---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${SECRET_DOMAIN}-cert"
  namespace: cert-manager
spec:
  commonName: "${SECRET_DOMAIN}"
  dnsNames:
    - "${SECRET_DOMAIN}"
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  secretName: "${SECRET_DOMAIN}-cert"
