---
creation_rules:
  - # IMPORTANT: This rule MUST be above the others
    path_regex: talos/.*\.sops\.ya?ml
    mac_only_encrypted: true
    key_groups:
      - age:
          - "age1r9dmr3ax8nuke3zhjgn3q9chvuwqy45lcflqfuecqc4psu40zfvq57xych"
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    mac_only_encrypted: true
    key_groups:
      - age:
          - "age1r9dmr3ax8nuke3zhjgn3q9chvuwqy45lcflqfuecqc4psu40zfvq57xych"
stores:
  yaml:
    indent: 2
