---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: desec-webhook
spec:
  interval: 30m
  chart:
    spec:
      chart: cert-manager-desec-webhook
      version: 1.0.1
      sourceRef:
        kind: HelmRepository
        name: desec
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    groupName: acme.${SECRET_DOMAIN}

    certManager:
      namespace: cert-manager
      serviceAccountName: cert-manager

    image:
      repository: ghcr.io/luzifer/cert-manager-desec-webhook
      tag: 1.0.1@sha256:fa1f6b2e9a6e62a2c231ce36ce638f5256784d60976c98c5179e9cb6a3332935
      pullPolicy: IfNotPresent

    secretName:
      - desec-token-secret
