---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: desec-http
spec:
  acme:
    email: "${SECRET_ACME_EMAIL}"
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cert-manager-desec-http-secret
    solvers:
    - dns01:
        webhook:
          groupName: "${SECRET_DOMAIN}"
          solverName: desec-http
          config:
            apiUrl: https://desec.io/api/v1
            domainName: "${SECRET_DOMAIN}"
            secretName: cert-domain-tls-key-"${SECRET_DOMAIN}"
            secretKeyName: desec-token
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: desec-http-staging
spec:
  acme:
    email: "${SECRET_ACME_EMAIL}"
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cert-manager-desec-http-secret
    solvers:
    - dns01:
        webhook:
          groupName: "${SECRET_DOMAIN}"
          solverName: desec-http
          config:
            apiUrl: https://desec.io/api/v1
            domainName: "${SECRET_DOMAIN}"
            secretName: cert-domain-tls-key-"${SECRET_DOMAIN}"
            secretKeyName: desec-token
