apiVersion: v1
kind: Secret
metadata:
    name: desec-token-secret
stringData:
    token: ENC[AES256_GCM,data:9K2+yLlX2+UwnjBxJOqmW1I9R3rwSo2fmaA6IA==,iv:oFQghoAmatjijJIV/vzTXoTHIuiCtYxt7m5P7p8ENt4=,tag:ZFYeuGQdYsB8Zmi8d6g3AA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r9dmr3ax8nuke3zhjgn3q9chvuwqy45lcflqfuecqc4psu40zfvq57xych
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3aXMyUVVEbTE3SDJVL1pa
            YkJkRlAwT25oSHR4L1BHbjlneGNSamNVL0VZClJtS29Ec3ZDeUI3b1A2QnVSaVZV
            a0pGOG5XZEx6cGJMaDNOT2x5SUVBSXMKLS0tIGRPUlRLMk05SnNZNS9rTkdKdHJi
            ckN5aXJIcVFJU1ZDSG1PK29EZnFna2MKsyZqDqoyR89GZ49Pag/xBQ/NFr3KAMfJ
            rYfhCXgG0iVESBioYe0EglObguxBxQl3hXF/qPQhc17TUdgJ0ReaUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-29T19:51:55Z"
    mac: ENC[AES256_GCM,data:Q+SHevgkIwmynJ6JGk6bqobxItN2pW5SvucOA9WmOC+wSgLrQit8ZDCdGk1G2FU5lplGQ/uybuyzTCIwyPVTc+Ctb+8uY4GvXoEpeH5e8jJ8VaF9ukioXz7nSCP68BBhtYhRwPP9Zrtsuv0mE9FatIe3lIOEryWeNvi6/kJW5JA=,iv:227RXOLljeInpGsvmR0F/uhSOE53hPT6pFsjkHP725k=,tag:t2JtKW7UQhZ3S3firrNnpQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
