---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rook-ceph-mon-endpoints
  namespace: rook-ceph-external
data:
  data: pve1=192.168.5.51:3300,pve2=192.168.5.52:3300,pve3=192.168.5.53:3300
  mapping: '{"node":{}}'
  maxMonId: "2"
